# Generated by Django 3.1.6 on 2021-03-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='e_roll',
            new_name='s_roll',
        ),
    ]
