# Generated by Django 3.1.6 on 2021-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_roll', models.IntegerField()),
                ('s_name', models.CharField(max_length=90)),
                ('s_address', models.CharField(max_length=90)),
                ('s_email', models.EmailField(max_length=90)),
                ('s_pass', models.CharField(max_length=90)),
            ],
        ),
    ]
