# Generated by Django 3.1.6 on 2021-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=90)),
                ('teacher_name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
    ]
